### ISSUE TITLE
method 'check' not supported

### ISSUE THREAD

**Issue by pansila** [messense/aliyundrive-webdav#288]
### 问题描述

Using a wevdavclient3 to connect to webdav server.

The test script:
```python
from webdav3.client import Client

options = {
    'webdav_hostname': "http://127.0.0.1:8080",
    'webdav_override_methods': {  # same error with or without this overriding
        'check': 'GET'
    },
}

client = Client(options)
client.verify = False
files = client.list()
print(files)
files = client.list('来自分享/学而思2022年退出，绝版课程')
print(files)
```

The error messages:
```
$ ./rsync.py
['来自分享/', '电影/']
Traceback (most recent call last):
  File "/home/zkm/temp/aliyundrive-webdav/./rsync.py", line 18, in <module>
    files = client.list('来自分享/学而思2022年退出，绝版课程')
  File "/usr/local/lib/python3.9/dist-packages/webdav3/client.py", line 67, in _wrapper
    res = fn(self, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/webdav3/client.py", line 260, in list
    if directory_urn.path() != Client.root and not self.check(directory_urn.path()):
  File "/usr/local/lib/python3.9/dist-packages/webdav3/client.py", line 67, in _wrapper
    res = fn(self, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/webdav3/client.py", line 297, in check
    response = self.execute_request(action='check', path=urn.quote())
  File "/usr/local/lib/python3.9/dist-packages/webdav3/client.py", line 228, in execute_request
    raise MethodNotSupported(name=action, server=self.webdav.hostname)
webdav3.exceptions.MethodNotSupported: Method 'check' not supported for http://127.0.0.1:8080
```

### 重现步骤

1. run webdav server with `cargo run --refresh-token=*******`
2. run the test script

### 版本

0ac70728b8775f5f4b9d23ab32f659a26d851550

### 运行平台

Debian 11.2

### 日志

```
2022-02-06T08:01:49.226863Z  INFO aliyundrive_webdav::drive: refresh token succeed refresh_token=*** nick_name=***
2022-02-06T08:01:49.226971Z  INFO aliyundrive_webdav::drive: found default drive drive_id=***
2022-02-06T08:01:49.227905Z DEBUG aliyundrive_webdav::vfs: dir cache initialized
2022-02-06T08:01:49.228683Z DEBUG aliyundrive_webdav: aliyundrive file system initialized
2022-02-06T08:01:49.228740Z DEBUG aliyundrive_webdav: webdav handler initialized read_buffer_size=10485760 auto_index=false
2022-02-06T08:01:49.228838Z  INFO aliyundrive_webdav: listening on http://0.0.0.0:8080
2022-02-06T08:01:57.575805Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/
2022-02-06T08:01:57.576121Z DEBUG aliyundrive_webdav::vfs: fs: read_dir path=/
2022-02-06T08:01:57.576193Z DEBUG aliyundrive_webdav::vfs: read_dir and cache path=/
2022-02-06T08:01:57.576269Z DEBUG aliyundrive_webdav::drive: list file drive_id=*** parent_file_id=root marker=None
2022-02-06T08:01:57.950146Z DEBUG aliyundrive_webdav::vfs: fs: metadata path=/来自分享/学而思2022年退出，绝版课程
2022-02-06T08:01:57.950228Z DEBUG aliyundrive_webdav::drive: get file by path drive_id=*** path=/来自分享/学而思2022年退出，绝版课程
```

**Comment by messense** [comment]
Try run it with `RUST_LOG=aliyundrive_webdav=debug,dav_server=debug` to see the logs from [dav-server-rs](https://github.com/messense/dav-server-rs).

**Comment by messense** [comment]
You can also disable check by adding `'disable_check': True` to `options` of the Python webdav client.

**Comment by pansila** [comment]
@messense Thanks, disabling check option works.
