### ISSUE TITLE
pip install aliyundrive-webdav 报错

### ISSUE THREAD

**Issue by MarsHou** [messense/aliyundrive-webdav#32]
root@OpenWrt:/# pip install aliyundrive-webdav
Collecting aliyundrive-webdav
  Using cached aliyundrive_webdav-0.1.25.tar.gz (416 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /tmp/pip-standalone-pip-s_n6o_1h/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3bw3spl8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.11,<0.12'
       cwd: None
  Complete output (52 lines):
  Collecting maturin<0.12,>=0.11
    Using cached maturin-0.11.3.tar.gz (110 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /tmp/tmpam39fzon build_wheel /tmp/tmp_eyx5z45
         cwd: /tmp/pip-install-sc2ngmux/maturin_9d7240e8a8b9472ab6f01872cf79ecc5
    Complete output (31 lines):
    running bdist_wheel
    running build
    installing to build/bdist.linux-aarch64/wheel
    running install
    Traceback (most recent call last):
      File "/tmp/tmpam39fzon", line 349, in <module>
        main()
      File "/tmp/tmpam39fzon", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpam39fzon", line 248, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-yop_47yn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-yop_47yn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-yop_47yn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 106, in <module>
        setup(
      File "/tmp/pip-build-env-yop_47yn/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      File "/tmp/pip-build-env-yop_47yn/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      File "setup.py", line 58, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------

本地相关版本号
root@OpenWrt:/# pip --version
pip 21.2.4 from /usr/lib/python3.8/site-packages/pip (python 3.8)

**Comment by messense** [comment]
openwrt 应该用 opkg 安装预编译的 ipk 包，不需要用 pip 来装。

**Comment by MarsHou** [comment]
> openwrt 应该用 opkg 安装预编译的 ipk 包，不需要用 pip 来装。

nice 多谢 已经成功用上了

**Comment by XenonChau** [comment]
那...不支持树莓派/阿里云运行么?

**Comment by messense** [comment]
@XenonChau 直接从 https://github.com/messense/aliyundrive-webdav/releases 下载。
