### ISSUE TITLE
无法正常启动程序并监听端口

### ISSUE THREAD

**Issue by ArcCal** [messense/aliyundrive-webdav#884]
### 问题描述

无法正常启动程序并监听端口

### 重现步骤

一、系统信息如下：
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

二、

### 版本

2.3.1

### 运行平台

Ubuntu 22.04.3 LTS ARM64

### 日志

snap run aliyundrive-webdav
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=749****
thread 'main' panicked at 'error binding to 0.0.0.0:8080: error creating server listener: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ArcCal** [comment]
运行snap run aliyundrive-webdav后，很长时间没有反应，然后会出现二维码，扫描后会出现报错

snap run aliyundrive-webdav
                                             
<unknown time>  INFO aliyundrive_webdav: Please scan the qrcode to login in 30 seconds
<unknown time>  INFO aliyundrive_webdav::drive: refresh token succeed
<unknown time>  INFO aliyundrive_webdav::drive: found default drive drive_id=749****
thread 'main' panicked at 'error binding to 0.0.0.0:8080: error creating server listener: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lestat220255** [comment]
same issue.

**Comment by gngpp** [comment]
很明显你当前的操作系统用户没有用8080端口的权限，给sudo试试

**Comment by eexpress** [comment]
```
⭕ sudo lsof -i :8080
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
aliyundri 11408 root   10u  IPv4 1256627      0t0  TCP *:webcache (LISTEN)
```
http://0.0.0.0:8080/ 一片空白？ 才安装的`aliyundrive-webdav-2.3.3-1.x86_64.rpm`。 fedora40。
